package org.server.core.model;
// Generated 2015-7-10 15:37:19 by Hibernate Tools 4.3.1



/**
 * Roominfo generated by hbm2java
 */
public class Roominfo  implements java.io.Serializable {


     private int roomId;
     private String roomName;
     private String roomDesc;
     private int gameId;
     private int roomStatus;
     private Double gameCoin;
     private Double minRequire;
     private int bankerLimit;
     private Double roomTs;
     private Integer roomOrder;
     private Double maxLimit;

    public Roominfo() {
    }

	
    public Roominfo(int roomId, String roomName, String roomDesc, int gameId, int roomStatus, int bankerLimit) {
        this.roomId = roomId;
        this.roomName = roomName;
        this.roomDesc = roomDesc;
        this.gameId = gameId;
        this.roomStatus = roomStatus;
        this.bankerLimit = bankerLimit;
    }
    public Roominfo(int roomId, String roomName, String roomDesc, int gameId, int roomStatus, Double gameCoin, Double minRequire, int bankerLimit, Double roomTs, Integer roomOrder, Double maxLimit) {
       this.roomId = roomId;
       this.roomName = roomName;
       this.roomDesc = roomDesc;
       this.gameId = gameId;
       this.roomStatus = roomStatus;
       this.gameCoin = gameCoin;
       this.minRequire = minRequire;
       this.bankerLimit = bankerLimit;
       this.roomTs = roomTs;
       this.roomOrder = roomOrder;
       this.maxLimit = maxLimit;
    }
   
    public int getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
    public String getRoomDesc() {
        return this.roomDesc;
    }
    
    public void setRoomDesc(String roomDesc) {
        this.roomDesc = roomDesc;
    }
    public int getGameId() {
        return this.gameId;
    }
    
    public void setGameId(int gameId) {
        this.gameId = gameId;
    }
    public int getRoomStatus() {
        return this.roomStatus;
    }
    
    public void setRoomStatus(int roomStatus) {
        this.roomStatus = roomStatus;
    }
    public Double getGameCoin() {
        return this.gameCoin;
    }
    
    public void setGameCoin(Double gameCoin) {
        this.gameCoin = gameCoin;
    }
    public Double getMinRequire() {
        return this.minRequire;
    }
    
    public void setMinRequire(Double minRequire) {
        this.minRequire = minRequire;
    }
    public int getBankerLimit() {
        return this.bankerLimit;
    }
    
    public void setBankerLimit(int bankerLimit) {
        this.bankerLimit = bankerLimit;
    }
    public Double getRoomTs() {
        return this.roomTs;
    }
    
    public void setRoomTs(Double roomTs) {
        this.roomTs = roomTs;
    }
    public Integer getRoomOrder() {
        return this.roomOrder;
    }
    
    public void setRoomOrder(Integer roomOrder) {
        this.roomOrder = roomOrder;
    }
    public Double getMaxLimit() {
        return this.maxLimit;
    }
    
    public void setMaxLimit(Double maxLimit) {
        this.maxLimit = maxLimit;
    }




}


