package org.server.core.model;
// Generated 2015-7-10 15:37:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userbasicinfo generated by hbm2java
 */
public class Userbasicinfo  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String userPass;
     private String status;
     private String userLevel;
     private Integer parentId;
     private Double bankCoin;
     private Double userMoney;
     private Integer userFc;
     private String regName;
     private String secQuestion;
     private String secHint;
     private String secAnswer;
     private String secEmail;
     private Integer userGender;
     private Date loginDate;
     private Integer accessTimes;
     private String loginIp;
     private Date startDate;

    public Userbasicinfo() {
    }

	
    public Userbasicinfo(int userId) {
        this.userId = userId;
    }
    public Userbasicinfo(int userId, String userName, String userPass, String status, String userLevel, Integer parentId, Double bankCoin, Double userMoney, Integer userFc, String regName, String secQuestion, String secHint, String secAnswer, String secEmail, Integer userGender, Date loginDate, Integer accessTimes, String loginIp, Date startDate) {
       this.userId = userId;
       this.userName = userName;
       this.userPass = userPass;
       this.status = status;
       this.userLevel = userLevel;
       this.parentId = parentId;
       this.bankCoin = bankCoin;
       this.userMoney = userMoney;
       this.userFc = userFc;
       this.regName = regName;
       this.secQuestion = secQuestion;
       this.secHint = secHint;
       this.secAnswer = secAnswer;
       this.secEmail = secEmail;
       this.userGender = userGender;
       this.loginDate = loginDate;
       this.accessTimes = accessTimes;
       this.loginIp = loginIp;
       this.startDate = startDate;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUserLevel() {
        return this.userLevel;
    }
    
    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    public Double getBankCoin() {
        return this.bankCoin;
    }
    
    public void setBankCoin(Double bankCoin) {
        this.bankCoin = bankCoin;
    }
    public Double getUserMoney() {
        return this.userMoney;
    }
    
    public void setUserMoney(Double userMoney) {
        this.userMoney = userMoney;
    }
    public Integer getUserFc() {
        return this.userFc;
    }
    
    public void setUserFc(Integer userFc) {
        this.userFc = userFc;
    }
    public String getRegName() {
        return this.regName;
    }
    
    public void setRegName(String regName) {
        this.regName = regName;
    }
    public String getSecQuestion() {
        return this.secQuestion;
    }
    
    public void setSecQuestion(String secQuestion) {
        this.secQuestion = secQuestion;
    }
    public String getSecHint() {
        return this.secHint;
    }
    
    public void setSecHint(String secHint) {
        this.secHint = secHint;
    }
    public String getSecAnswer() {
        return this.secAnswer;
    }
    
    public void setSecAnswer(String secAnswer) {
        this.secAnswer = secAnswer;
    }
    public String getSecEmail() {
        return this.secEmail;
    }
    
    public void setSecEmail(String secEmail) {
        this.secEmail = secEmail;
    }
    public Integer getUserGender() {
        return this.userGender;
    }
    
    public void setUserGender(Integer userGender) {
        this.userGender = userGender;
    }
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
    public Integer getAccessTimes() {
        return this.accessTimes;
    }
    
    public void setAccessTimes(Integer accessTimes) {
        this.accessTimes = accessTimes;
    }
    public String getLoginIp() {
        return this.loginIp;
    }
    
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }




}


